### ISSUE TITLE
Add a simple variable replacement templating syntax for fixtures

### ISSUE THREAD

**Issue by croach** [croach/Flask-Fixtures#8]
In several situations, the developer has added constants to their code that the test test writer would like to reference in the tests. Doing so allows tests to remain unchanged when changes to the value of said constants happen in the codebase. This feature would add a pre-processing step to the ingestion of fixture files that would allow test writers to reference variables within python modules.

For example,

``` yaml
- table: employees
  records:
    - id: 1
      name: Winston Smith
      email: #{ oceania.models.WINSTON_SMITH_EMAIL }
```

``` json
{
    "table": "employees",
    "records": [{
        "id": 1,
        "name": "Winston Smith",
        "email": "#{ oceania.models.WINSTON_SMITH_EMAIL }"
    }]
}
```
